version: '3.8'

services:
  chatbot:
    build: .
    container_name: chatbot-amitie
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./documents:/app/documents
      - ./faiss_clinique_amitie:/app/faiss_clinique_amitie
